Update docsy theme to docsy v0.6.0
google/docsy-example pull request #192
Opened 2022-12-05 19:05 UTC by geriom

Update the theme, the README file, and the hugo and go versions.

2022-12-28 10:31 UTC, deining requested changes
I spotted some minor quirks, once these are corrected, PR is ready for merging.

2022-12-28 10:31 UTC, deining commented on go.mod
>  	github.com/FortAwesome/Font-Awesome v0.0.0-20220831210243-d3a7818c253f // indirect
This is not the latest version of Font-Awesome, this line should read:

```
	github.com/FortAwesome/Font-Awesome v0.0.0-20221115183454-96cafbd73ec4 // indirect
```

Use this command for upgrade:

```
hugo mod get -u github.com/FortAwesome/Font-Awesome@96cafbd73ec4
```

2022-12-28 10:31 UTC, deining commented on README.md
> +github.com/FortAwesome/Font-Awesome@v0.0.0-20220831210243-d3a7818c253f
Output does not show the latest version of Font-Awesome, should be:

```
github.com/FortAwesome/Font-Awesome v0.0.0-20221115183454-96cafbd73ec4
```

2022-12-28 10:31 UTC, deining commented on netlify.toml
> +HUGO_VERSION = "0.107.0"
Latest `hugo` version is `0.109.0` now.

2022-12-28 10:31 UTC, deining commented on netlify.toml
> +GO_VERSION = "1.19.3"
Latest `go` version is `1.19.4` now.

2022-12-28 11:02 UTC, deining commented
Deploy on Netlify fails for whatever reason. When trying to check the logs, I'm present with an empty log window, with a whell spinning forever. Looks like the netlify task is stuck and needs restart/maintenance. Is anyone able to fix that?

2023-02-10 15:53 UTC, deining commented on go.mod
>  	github.com/FortAwesome/Font-Awesome v0.0.0-20220831210243-d3a7818c253f // indirect
Resolved with commit 3031c33b5e0b.

2023-02-10 15:53 UTC, deining commented on README.md
> +github.com/FortAwesome/Font-Awesome@v0.0.0-20220831210243-d3a7818c253f
Resolved with commit 3031c33b5e0b.

2023-02-10 15:53 UTC, deining commented on netlify.toml
> +GO_VERSION = "1.19.3"
Resolved with commit 3031c33b5e0b.

2023-02-10 15:59 UTC, deining commented
> Deploy on Netlify fails due to to the use of unsupported Ubuntu 16.04 (Xenial) build image.

With this topic being resolved, I just resolved the outstanding issues raised by me a while ago.

@LisaFC @geriom: can you please have a final look here? Would like to see this merged. We are referring to the this example repo as recommended setup method in the user guide, so this repo should point to the latest official release of docsy. Thanks.

2023-06-09 10:23 UTC, chalin commented
@deining - better late than never? Shall we merge this now before updating to 0.7.0?

2023-06-09 11:47 UTC, chalin commented
I'm going to go ahead and merge. We can address any required changes in the 0.7.0 PR.

2023-06-09 11:47 UTC, merged

2023-06-09 15:17 UTC, chalin commented
> Great, thanks. With this PR merged, we should at least add a tag `v0.6.0` (and maybe even add `v0.6.0` as release). WDYT?

Good idea, thanks. Can take care of that?

2023-06-09 20:58 UTC, deining commented
> Good idea, thanks. Can take care of that?

Done.

2023-06-09 21:20 UTC, chalin commented
Wonderful! 🎉