Change the default baseURL as example.org
google/docsy-example pull request #205
Opened 2023-05-07 02:52 UTC by razonyang

A minor change that allow clicking the URL from console.

```sh
hugo server
...
Web Server is available at //localhost:1313/ (bind address 127.0.0.1)
```

With this PR:

```sh
hugo server
...
Web Server is available at http://localhost:1313/ (bind address 127.0.0.1)
```

2023-06-26 20:53 UTC, deining approved these changes
LGTM.

2023-11-17 14:54 UTC, chalin requested changes
The baseURL should match the currently hosted site path.

/cc @emckean @LisaFC @geriom

2023-11-17 21:31 UTC, deining commented
Can you please rebase and resolve merge conflicts? Thanks.

2023-11-17 21:47 UTC, razonyang commented
Done, seems there are a lot of changes, I re-fork and apply the changes on new configuration file.

2023-11-17 21:54 UTC, chalin approved these changes
Thanks!

2024-03-21 21:03 UTC, merged